// <auto-generated />
using L04_LinqToEntities_HW;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace L04_LinqToEntities_HW.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("L04_LinqToEntities_HW.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is Product 1",
                            IsAvailable = true,
                            Name = "Product 1",
                            Price = 120m
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is Product 2",
                            IsAvailable = false,
                            Name = "Product 2",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is Product 3",
                            IsAvailable = true,
                            Name = "Product 3",
                            Price = 125m
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is Product 4",
                            IsAvailable = true,
                            Name = "Product 4",
                            Price = 264m
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is Product 5",
                            IsAvailable = false,
                            Name = "Product 5",
                            Price = 210m
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is Product 6",
                            IsAvailable = true,
                            Name = "Product 6",
                            Price = 430m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
