// <auto-generated />
using L03_RelationshipsBetweenModels_HW1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace L03_RelationshipsBetweenModels_HW1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("L03_RelationshipsBetweenModels_HW1.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Dnipro"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Rivne"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Zakopane"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Gdynia"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Wroclaw"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            Name = "Turin"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Naples"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 4,
                            Name = "Montreal"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 4,
                            Name = "Ottawa"
                        });
                });

            modelBuilder.Entity("L03_RelationshipsBetweenModels_HW1.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canada"
                        });
                });

            modelBuilder.Entity("L03_RelationshipsBetweenModels_HW1.City", b =>
                {
                    b.HasOne("L03_RelationshipsBetweenModels_HW1.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
